# Generated by Django 4.1.13 on 2024-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_category_items_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='items',
            name='review_avg',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='total_reviews',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
