# Generated by Django 4.1.13 on 2024-07-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_category_options_items_review_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='review_avg',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='items',
            name='total_reviews',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
